### ISSUE TITLE
Java-client logs null pointer exception

### ISSUE THREAD

**Issue by prajeeva-crunchbase** [splitio/java-client#251]
java-client sees the following issue in version: 4.2.1:

```
java.lang.NullPointerException: null
    at io.split.telemetry.storage.InMemoryTelemetryStorage.recordLatency(InMemoryTelemetryStorage.java:111)
    at io.split.client.SplitClientImpl.track(SplitClientImpl.java:179)
    at io.split.client.SplitClientImpl.track(SplitClientImpl.java:128)
```
version: 4.2.1(latest)

library works as expected but the log has potential to cause unnecessary noise.

**Comment by chillaq** [comment]
Hi @prajeeva-crunchbase , thanks for the info, checking with the team.
